POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "first_name": "נועם",
  "surname": "רביב",
  "email": "noam@example.com",
  "phone_no": "052-1133322",
  "password": "strongpassword789",
  "permissions_id": 4,
  "branch_id": 15608
}
### Login existing user
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "moshe@example.com",
  "password": "strongpassword456",
  "phone_no": "052-1144422",
  "permissions_id": 2,
}

### Get all pending supplier requests
GET http://localhost:5000/api/supplier-requests/pending

### Login existing user
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "moshe@example.com",
  "password": "strongpassword456"
}